//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Shop.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAREKETLER
    {
        public int ID { get; set; }
        public Nullable<int> KITAP { get; set; }
        public Nullable<int> MUSTERI { get; set; }
        public Nullable<decimal> BIRIMFIYAT { get; set; }
        public Nullable<int> ADET { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> KASAID { get; set; }
    
        public virtual KITAPLAR KITAPLAR { get; set; }
        public virtual MUSTERILER MUSTERILER { get; set; }
        public virtual KASA KASA { get; set; }
    }
}
