//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Shop.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KITAPLAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KITAPLAR()
        {
            this.HAREKETLER = new HashSet<HAREKETLER>();
            this.KITAPYORUM = new HashSet<KITAPYORUM>();
        }
    
        public int ID { get; set; }
        public string AD { get; set; }
        public Nullable<byte> KATEGORI { get; set; }
        public Nullable<short> YAZAR { get; set; }
        public string BASIMYIL { get; set; }
        public string SAYFA { get; set; }
        public string YAYINEVI { get; set; }
        public Nullable<int> STOK { get; set; }
        public string KITAPRESIM { get; set; }
        public string KITAPOZET { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HAREKETLER> HAREKETLER { get; set; }
        public virtual KATEGORILER KATEGORILER { get; set; }
        public virtual YAZARLAR YAZARLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KITAPYORUM> KITAPYORUM { get; set; }
    }
}
