//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Shop.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONELLER
    {
        public byte ID { get; set; }
        public string PERSONEL { get; set; }
        public string MAIL { get; set; }
        public Nullable<bool> DURUM { get; set; }
    }
}
